# Scraping product category
## Category level 1

In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from lxml import etree
import time
from urllib.parse import urlparse, parse_qs

In [2]:
def get_category_lv1_title(url, session):
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8',
        'Accept-Language': 'th-TH,th;q=0.9,en-US;q=0.8,en;q=0.7',
        'Referer': 'https://www.naiin.com/',
    }

    parsed_url = urlparse(url)
    params = parse_qs(parsed_url.query)
    p_id = params.get('product_type_id', [''])[0]
    cat1_code = params.get('category_1_code', [''])[0]

    # เตรียมข้อมูลพื้นฐานรอไว้ก่อน
    data = {
        'product_type_id': p_id,
        'category_1_code': cat1_code,
        'category_1_title': "-", # Default เป็น "-"
        'status_code': None,
        'url': url
    }

    try:
        response = session.get(url, headers=headers, timeout=15)
        data['status_code'] = response.status_code

        # ตรวจสอบว่าถ้าเป็น 200 OK ถึงจะทำการ Parse หา Title
        if response.status_code == 200:
            soup = BeautifulSoup(response.text, 'lxml')
            h1_tag = soup.find('h1', class_='tw-text-center')
            if h1_tag:
                data['category_1_title'] = h1_tag.get_text(strip=True)
        else:
            print(f"Skipping Title: Received Status {response.status_code} for {url}")

    except Exception as e:
        print(f"Network/Request Error at {url}: {e}")
        data['status_code'] = "Error"

    return data

def get_product_level_1():
    sitemap_url = "https://storage.naiin.com/system/application/bookstore/resource/sitemap/sitemap_CategoryLv1.xml"
    print("Fetching Category Level 1 Sitemap...")

    try:
        response = requests.get(sitemap_url)
        root = etree.fromstring(response.content)
        namespaces = {'ns': 'http://www.sitemaps.org/schemas/sitemap/0.9'}
        all_urls = root.xpath('//ns:loc/text()', namespaces=namespaces)
    except Exception as e:
        print(f"Failed to read sitemap: {e}")
        return

    target_urls = [u for u in all_urls]
    print(f"Total target Level 1 URLs: {len(target_urls)}")

    results = []

    with requests.Session() as session:
        for i, url in enumerate(target_urls):
            print(f"[{i+1}/{len(target_urls)}] Scraping: {url}")

            data = get_category_lv1_title(url, session)
            results.append(data)

            time.sleep(1) 

    df = pd.DataFrame(results)
    return df

In [3]:
cat_lv1_df = get_product_level_1()

Fetching Category Level 1 Sitemap...
Total target Level 1 URLs: 55
[1/55] Scraping: https://www.naiin.com/category?category_1_code=1&product_type_id=1
[2/55] Scraping: https://www.naiin.com/category?category_1_code=2&product_type_id=1
[3/55] Scraping: https://www.naiin.com/category?category_1_code=3&product_type_id=1
[4/55] Scraping: https://www.naiin.com/category?category_1_code=4&product_type_id=1
[5/55] Scraping: https://www.naiin.com/category?category_1_code=5&product_type_id=1
[6/55] Scraping: https://www.naiin.com/category?category_1_code=8&product_type_id=1
[7/55] Scraping: https://www.naiin.com/category?category_1_code=9&product_type_id=1
[8/55] Scraping: https://www.naiin.com/category?category_1_code=10&product_type_id=1
[9/55] Scraping: https://www.naiin.com/category?category_1_code=11&product_type_id=1
[10/55] Scraping: https://www.naiin.com/category?category_1_code=12&product_type_id=1
[11/55] Scraping: https://www.naiin.com/category?category_1_code=13&product_type_id=1
[12/55] Scraping: https://www.naiin.com/category?category_1_code=14&product_type_id=1
[13/55] Scraping: https://www.naiin.com/category?category_1_code=15&product_type_id=1
[14/55] Scraping: https://www.naiin.com/category?category_1_code=16&product_type_id=1
[15/55] Scraping: https://www.naiin.com/category?category_1_code=17&product_type_id=1
[16/55] Scraping: https://www.naiin.com/category?category_1_code=19&product_type_id=1
[17/55] Scraping: https://www.naiin.com/category?category_1_code=20&product_type_id=1
[18/55] Scraping: https://www.naiin.com/category?category_1_code=28&product_type_id=1
[19/55] Scraping: https://www.naiin.com/category?category_1_code=33&product_type_id=1
[20/55] Scraping: https://www.naiin.com/category?category_1_code=34&product_type_id=1
[21/55] Scraping: https://www.naiin.com/category?category_1_code=35&product_type_id=1
[22/55] Scraping: https://www.naiin.com/category?category_1_code=36&product_type_id=1
Skipping Title: Received Status 404 for https://www.naiin.com/category?category_1_code=36&product_type_id=1
[23/55] Scraping: https://www.naiin.com/category?category_1_code=35&product_type_id=2
Skipping Title: Received Status 404 for https://www.naiin.com/category?category_1_code=35&product_type_id=2
[24/55] Scraping: https://www.naiin.com/category?category_1_code=36&product_type_id=2
[25/55] Scraping: https://www.naiin.com/category?category_1_code=1&product_type_id=3
[26/55] Scraping: https://www.naiin.com/category?category_1_code=2&product_type_id=3
[27/55] Scraping: https://www.naiin.com/category?category_1_code=3&product_type_id=3
[28/55] Scraping: https://www.naiin.com/category?category_1_code=4&product_type_id=3
[29/55] Scraping: https://www.naiin.com/category?category_1_code=5&product_type_id=3
[30/55] Scraping: https://www.naiin.com/category?category_1_code=8&product_type_id=3
[31/55] Scraping: https://www.naiin.com/category?category_1_code=9&product_type_id=3
[32/55] Scraping: https://www.naiin.com/category?category_1_code=10&product_type_id=3
[33/55] Scraping: https://www.naiin.com/category?category_1_code=11&product_type_id=3
[34/55] Scraping: https://www.naiin.com/category?category_1_code=12&product_type_id=3
[35/55] Scraping: https://www.naiin.com/category?category_1_code=13&product_type_id=3
[36/55] Scraping: https://www.naiin.com/category?category_1_code=14&product_type_id=3
[37/55] Scraping: https://www.naiin.com/category?category_1_code=15&product_type_id=3
[38/55] Scraping: https://www.naiin.com/category?category_1_code=16&product_type_id=3
[39/55] Scraping: https://www.naiin.com/category?category_1_code=17&product_type_id=3
[40/55] Scraping: https://www.naiin.com/category?category_1_code=19&product_type_id=3
[41/55] Scraping: https://www.naiin.com/category?category_1_code=20&product_type_id=3
[42/55] Scraping: https://www.naiin.com/category?category_1_code=28&product_type_id=3
[43/55] Scraping: https://www.naiin.com/category?category_1_code=33&product_type_id=3
[44/55] Scraping: https://www.naiin.com/category?category_1_code=34&product_type_id=3
[45/55] Scraping: https://www.naiin.com/category?category_1_code=17&product_type_id=4
[46/55] Scraping: https://www.naiin.com/category?category_1_code=35&product_type_id=4
[47/55] Scraping: https://www.naiin.com/category?category_1_code=36&product_type_id=4
[48/55] Scraping: https://www.naiin.com/category?category_1_code=35&product_type_id=7
Skipping Title: Received Status 404 for https://www.naiin.com/category?category_1_code=35&product_type_id=7
[49/55] Scraping: https://www.naiin.com/category?category_1_code=36&product_type_id=7
Skipping Title: Received Status 404 for https://www.naiin.com/category?category_1_code=36&product_type_id=7
[50/55] Scraping: https://www.naiin.com/category?category_1_code=21&product_type_id=8
[51/55] Scraping: https://www.naiin.com/category?category_1_code=23&product_type_id=8
[52/55] Scraping: https://www.naiin.com/category?category_1_code=25&product_type_id=8
Skipping Title: Received Status 404 for https://www.naiin.com/category?category_1_code=25&product_type_id=8
[53/55] Scraping: https://www.naiin.com/category?category_1_code=26&product_type_id=8
[54/55] Scraping: https://www.naiin.com/category?category_1_code=31&product_type_id=8
[55/55] Scraping: https://www.naiin.com/category?category_1_code=35&product_type_id=8

In [4]:
cat_lv1_df

,product_type_id,category_1_code,category_1_title,status_code,url
0,1,1,หนังสือพระราชนิพนธ์,200,https://www.naiin.com/category?category_1_code...
1,1,2,นิยาย,200,https://www.naiin.com/category?category_1_code...
2,1,3,หนังสือวาย ยูริ,200,https://www.naiin.com/category?category_1_code...
3,1,4,หนังสือท่องเที่ยว,200,https://www.naiin.com/category?category_1_code...
4,1,5,บ้านและสวน,200,https://www.naiin.com/category?category_1_code...
5,1,8,งานอดิเรก งานฝีมือ,200,https://www.naiin.com/category?category_1_code...
6,1,9,สุขภาพ ความงาม,200,https://www.naiin.com/category?category_1_code...
7,1,10,แม่และเด็ก,200,https://www.naiin.com/category?category_1_code...
8,1,11,ธรรมะ ศาสนา และปรัชญา,200,https://www.naiin.com/category?category_1_code...
9,1,12,โหราศาสตร์ ดูดวง ฮวงจุ้ย,200,https://www.naiin.com/category?category_1_code...
10,1,13,จิตวิทยา การพัฒนาตัวเอง,200,https://www.naiin.com/category?category_1_code...
11,1,14,การ์ตูน,200,https://www.naiin.com/category?category_1_code...
12,1,15,บริหาร ธุรกิจ,200,https://www.naiin.com/category?category_1_code...
13,1,16,คอมพิวเตอร์,200,https://www.naiin.com/category?category_1_code...
14,1,17,หนังสือเตรียมสอบ แนวข้อสอบ,200,https://www.naiin.com/category?category_1_code...
15,1,19,หนังสือเด็ก,200,https://www.naiin.com/category?category_1_code...
16,1,20,หนังสือต่างประเทศ,200,https://www.naiin.com/category?category_1_code...
17,1,28,นิยายแปล,200,https://www.naiin.com/category?category_1_code...
18,1,33,วรรณกรรม,200,https://www.naiin.com/category?category_1_code...
19,1,34,หนังสือบทความ สารคดี,200,https://www.naiin.com/category?category_1_code...
20,1,35,สินค้าไลฟ์สไตล์,200,https://www.naiin.com/category?category_1_code...
21,1,36,-,404,https://www.naiin.com/category?category_1_code...
22,2,35,-,404,https://www.naiin.com/category?category_1_code...
23,2,36,Magazine,200,https://www.naiin.com/category?category_1_code...
24,3,1,หนังสือพระราชนิพนธ์,200,https://www.naiin.com/category?category_1_code...
25,3,2,นิยาย,200,https://www.naiin.com/category?category_1_code...
26,3,3,หนังสือวาย ยูริ,200,https://www.naiin.com/category?category_1_code...
27,3,4,หนังสือท่องเที่ยว,200,https://www.naiin.com/category?category_1_code...
28,3,5,บ้านและสวน,200,https://www.naiin.com/category?category_1_code...
29,3,8,งานอดิเรก งานฝีมือ,200,https://www.naiin.com/category?category_1_code...
30,3,9,สุขภาพ ความงาม,200,https://www.naiin.com/category?category_1_code...
31,3,10,แม่และเด็ก,200,https://www.naiin.com/category?category_1_code...
32,3,11,ธรรมะ ศาสนา และปรัชญา,200,https://www.naiin.com/category?category_1_code...
33,3,12,โหราศาสตร์ ดูดวง ฮวงจุ้ย,200,https://www.naiin.com/category?category_1_code...
34,3,13,จิตวิทยา การพัฒนาตัวเอง,200,https://www.naiin.com/category?category_1_code...
35,3,14,การ์ตูน,200,https://www.naiin.com/category?category_1_code...
36,3,15,บริหาร ธุรกิจ,200,https://www.naiin.com/category?category_1_code...
37,3,16,คอมพิวเตอร์,200,https://www.naiin.com/category?category_1_code...
38,3,17,หนังสือเตรียมสอบ แนวข้อสอบ,200,https://www.naiin.com/category?category_1_code...
39,3,19,หนังสือเด็ก,200,https://www.naiin.com/category?category_1_code...
40,3,20,หนังสือต่างประเทศ,200,https://www.naiin.com/category?category_1_code...
41,3,28,นิยายแปล,200,https://www.naiin.com/category?category_1_code...
42,3,33,วรรณกรรม,200,https://www.naiin.com/category?category_1_code...
43,3,34,หนังสือบทความ สารคดี,200,https://www.naiin.com/category?category_1_code...
44,4,17,หนังสือเตรียมสอบ แนวข้อสอบ,200,https://www.naiin.com/category?category_1_code...
45,4,35,สินค้าไลฟ์สไตล์,200,https://www.naiin.com/category?category_1_code...
46,4,36,Magazine,200,https://www.naiin.com/category?category_1_code...
47,7,35,-,404,https://www.naiin.com/category?category_1_code...
48,7,36,-,404,https://www.naiin.com/category?category_1_code...
49,8,21,อุปกรณ์เครื่องเขียน เครื่องใช้สำนักงาน,200,https://www.naiin.com/category?category_1_code...
50,8,23,สินค้าเพื่อสุขภาพความงาม ของใช้ส่วนตัว,200,https://www.naiin.com/category?category_1_code...
51,8,25,-,404,https://www.naiin.com/category?category_1_code...
52,8,26,อาหารและเครื่องดื่ม,200,https://www.naiin.com/category?category_1_code...
53,8,31,ของเล่นเด็ก เสริมทักษะและการเรียนรู้,200,https://www.naiin.com/category?category_1_code...
54,8,35,สินค้าไลฟ์สไตล์,200,https://www.naiin.com/category?category_1_code...

In [5]:
import os
import pandas as pd

# 1. Get the current directory
current_directory = os.getcwd()

# 2. ระบุปลายทางไปที่โฟลเดอร์ /data
output_path = os.path.join(current_directory, "..", "data", "prod_cat_lv1.csv")

# 3. บันทึกไฟล์ด้วย Path ที่สร้างขึ้น
os.makedirs(os.path.dirname(output_path), exist_ok=True)
cat_lv1_df.to_csv(output_path, index=False, encoding='utf-8-sig', mode = 'w')

print(f"✅ Saved product URLs to: {output_path}")

✅ Saved product URLs to: d:\Project\book-scrap\ingestion\..\data\prod_cat_lv1.csv

## Category level 2

In [6]:
def get_category_lv2_title(url, session):
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8',
        'Accept-Language': 'th-TH,th;q=0.9,en-US;q=0.8,en;q=0.7',
        'Referer': 'https://www.naiin.com/',
    }

    parsed_url = urlparse(url)
    params = parse_qs(parsed_url.query)
    p_id = params.get('product_type_id', [''])[0]
    cat1_code = params.get('category_1_code', [''])[0]
    cat2_code = params.get('categoryLv2Code', [''])[0]

    data = {
        'product_type_id': p_id,
        'category_1_code': cat1_code,
        'category_2_code': cat2_code,
        'category_2_title': "-",
        'status_code': None,
        'url': url
    }

    try:
        response = session.get(url, headers=headers, timeout=15)
        data['status_code'] = response.status_code

        if response.status_code == 200:
            soup = BeautifulSoup(response.text, 'lxml')
            h1_tag = soup.find('h1', class_='tw-text-center')
            if h1_tag:
                data['category_2_title'] = h1_tag.get_text(strip=True)
        else:
            print(f"  [!] Status {response.status_code} for {url}")

    except Exception as e:
        print(f"  [!] Error at {url}: {e}")
        data['status_code'] = "Error"

    return data

def get_product_level_2():
    sitemap_url = "https://storage.naiin.com/system/application/bookstore/resource/sitemap/sitemap_CategoryLv2.xml"
    print("Fetching Category Level 2 Sitemap...")

    try:
        response = requests.get(sitemap_url)
        root = etree.fromstring(response.content)
        namespaces = {'ns': 'http://www.sitemaps.org/schemas/sitemap/0.9'}
        all_urls = root.xpath('//ns:loc/text()', namespaces=namespaces)
    except Exception as e:
        print(f"Failed to read sitemap: {e}")
        return None

    target_urls = [u for u in all_urls]
    print(f"Total target URLs: {len(target_urls)}")

    results = []

    with requests.Session() as session:
        for i, url in enumerate(target_urls):
            print(f"[{i+1}/{len(target_urls)}] Scraping: {url}")

            data = get_category_lv2_title(url, session)
            results.append(data)

            time.sleep(1) 

    df = pd.DataFrame(results)

    return df

In [7]:
cat_lv2_df = get_product_level_2()

Fetching Category Level 2 Sitemap...
Total target URLs: 190
[1/190] Scraping: https://www.naiin.com/category?category_1_code=1&categoryLv2Code=54&product_type_id=1
[2/190] Scraping: https://www.naiin.com/category?category_1_code=1&categoryLv2Code=135&product_type_id=1
[3/190] Scraping: https://www.naiin.com/category?category_1_code=2&categoryLv2Code=6&product_type_id=1
[4/190] Scraping: https://www.naiin.com/category?category_1_code=2&categoryLv2Code=7&product_type_id=1
[5/190] Scraping: https://www.naiin.com/category?category_1_code=2&categoryLv2Code=8&product_type_id=1
[6/190] Scraping: https://www.naiin.com/category?category_1_code=2&categoryLv2Code=86&product_type_id=1
[7/190] Scraping: https://www.naiin.com/category?category_1_code=2&categoryLv2Code=134&product_type_id=1
[8/190] Scraping: https://www.naiin.com/category?category_1_code=3&categoryLv2Code=95&product_type_id=1
[9/190] Scraping: https://www.naiin.com/category?category_1_code=3&categoryLv2Code=140&product_type_id=1
[10/190] Scraping: https://www.naiin.com/category?category_1_code=4&categoryLv2Code=51&product_type_id=1
[11/190] Scraping: https://www.naiin.com/category?category_1_code=4&categoryLv2Code=52&product_type_id=1
[12/190] Scraping: https://www.naiin.com/category?category_1_code=4&categoryLv2Code=53&product_type_id=1
[13/190] Scraping: https://www.naiin.com/category?category_1_code=5&categoryLv2Code=56&product_type_id=1
[14/190] Scraping: https://www.naiin.com/category?category_1_code=8&categoryLv2Code=22&product_type_id=1
[15/190] Scraping: https://www.naiin.com/category?category_1_code=8&categoryLv2Code=57&product_type_id=1
[16/190] Scraping: https://www.naiin.com/category?category_1_code=8&categoryLv2Code=58&product_type_id=1
[17/190] Scraping: https://www.naiin.com/category?category_1_code=8&categoryLv2Code=59&product_type_id=1
[18/190] Scraping: https://www.naiin.com/category?category_1_code=9&categoryLv2Code=60&product_type_id=1
[19/190] Scraping: https://www.naiin.com/category?category_1_code=10&categoryLv2Code=61&product_type_id=1
[20/190] Scraping: https://www.naiin.com/category?category_1_code=11&categoryLv2Code=43&product_type_id=1
[21/190] Scraping: https://www.naiin.com/category?category_1_code=12&categoryLv2Code=62&product_type_id=1
[22/190] Scraping: https://www.naiin.com/category?category_1_code=13&categoryLv2Code=63&product_type_id=1
[23/190] Scraping: https://www.naiin.com/category?category_1_code=13&categoryLv2Code=139&product_type_id=1
[24/190] Scraping: https://www.naiin.com/category?category_1_code=14&categoryLv2Code=32&product_type_id=1
[25/190] Scraping: https://www.naiin.com/category?category_1_code=14&categoryLv2Code=33&product_type_id=1
[26/190] Scraping: https://www.naiin.com/category?category_1_code=14&categoryLv2Code=34&product_type_id=1
  [!] Status 404 for https://www.naiin.com/category?category_1_code=14&categoryLv2Code=34&product_type_id=1
[27/190] Scraping: https://www.naiin.com/category?category_1_code=14&categoryLv2Code=35&product_type_id=1
  [!] Status 404 for https://www.naiin.com/category?category_1_code=14&categoryLv2Code=35&product_type_id=1
[28/190] Scraping: https://www.naiin.com/category?category_1_code=14&categoryLv2Code=37&product_type_id=1
[29/190] Scraping: https://www.naiin.com/category?category_1_code=14&categoryLv2Code=38&product_type_id=1
[30/190] Scraping: https://www.naiin.com/category?category_1_code=14&categoryLv2Code=40&product_type_id=1
  [!] Status 404 for https://www.naiin.com/category?category_1_code=14&categoryLv2Code=40&product_type_id=1
[31/190] Scraping: https://www.naiin.com/category?category_1_code=15&categoryLv2Code=47&product_type_id=1
[32/190] Scraping: https://www.naiin.com/category?category_1_code=15&categoryLv2Code=48&product_type_id=1
[33/190] Scraping: https://www.naiin.com/category?category_1_code=15&categoryLv2Code=49&product_type_id=1
[34/190] Scraping: https://www.naiin.com/category?category_1_code=15&categoryLv2Code=138&product_type_id=1
[35/190] Scraping: https://www.naiin.com/category?category_1_code=16&categoryLv2Code=64&product_type_id=1
[36/190] Scraping: https://www.naiin.com/category?category_1_code=16&categoryLv2Code=136&product_type_id=1
[37/190] Scraping: https://www.naiin.com/category?category_1_code=16&categoryLv2Code=137&product_type_id=1
[38/190] Scraping: https://www.naiin.com/category?category_1_code=17&categoryLv2Code=11&product_type_id=1
[39/190] Scraping: https://www.naiin.com/category?category_1_code=17&categoryLv2Code=14&product_type_id=1
[40/190] Scraping: https://www.naiin.com/category?category_1_code=17&categoryLv2Code=15&product_type_id=1
[41/190] Scraping: https://www.naiin.com/category?category_1_code=17&categoryLv2Code=16&product_type_id=1
[42/190] Scraping: https://www.naiin.com/category?category_1_code=17&categoryLv2Code=19&product_type_id=1
[43/190] Scraping: https://www.naiin.com/category?category_1_code=17&categoryLv2Code=20&product_type_id=1
[44/190] Scraping: https://www.naiin.com/category?category_1_code=17&categoryLv2Code=21&product_type_id=1
[45/190] Scraping: https://www.naiin.com/category?category_1_code=17&categoryLv2Code=23&product_type_id=1
[46/190] Scraping: https://www.naiin.com/category?category_1_code=17&categoryLv2Code=141&product_type_id=1
[47/190] Scraping: https://www.naiin.com/category?category_1_code=17&categoryLv2Code=142&product_type_id=1
[48/190] Scraping: https://www.naiin.com/category?category_1_code=17&categoryLv2Code=143&product_type_id=1
[49/190] Scraping: https://www.naiin.com/category?category_1_code=17&categoryLv2Code=144&product_type_id=1
[50/190] Scraping: https://www.naiin.com/category?category_1_code=17&categoryLv2Code=145&product_type_id=1
[51/190] Scraping: https://www.naiin.com/category?category_1_code=17&categoryLv2Code=146&product_type_id=1
[52/190] Scraping: https://www.naiin.com/category?category_1_code=17&categoryLv2Code=147&product_type_id=1
[53/190] Scraping: https://www.naiin.com/category?category_1_code=17&categoryLv2Code=148&product_type_id=1
[54/190] Scraping: https://www.naiin.com/category?category_1_code=17&categoryLv2Code=149&product_type_id=1
[55/190] Scraping: https://www.naiin.com/category?category_1_code=17&categoryLv2Code=150&product_type_id=1
[56/190] Scraping: https://www.naiin.com/category?category_1_code=17&categoryLv2Code=151&product_type_id=1
[57/190] Scraping: https://www.naiin.com/category?category_1_code=17&categoryLv2Code=152&product_type_id=1
[58/190] Scraping: https://www.naiin.com/category?category_1_code=17&categoryLv2Code=153&product_type_id=1
[59/190] Scraping: https://www.naiin.com/category?category_1_code=17&categoryLv2Code=154&product_type_id=1
[60/190] Scraping: https://www.naiin.com/category?category_1_code=17&categoryLv2Code=155&product_type_id=1
  [!] Status 404 for https://www.naiin.com/category?category_1_code=17&categoryLv2Code=155&product_type_id=1
[61/190] Scraping: https://www.naiin.com/category?category_1_code=17&categoryLv2Code=156&product_type_id=1
  [!] Status 404 for https://www.naiin.com/category?category_1_code=17&categoryLv2Code=156&product_type_id=1
[62/190] Scraping: https://www.naiin.com/category?category_1_code=17&categoryLv2Code=157&product_type_id=1
[63/190] Scraping: https://www.naiin.com/category?category_1_code=19&categoryLv2Code=24&product_type_id=1
[64/190] Scraping: https://www.naiin.com/category?category_1_code=19&categoryLv2Code=26&product_type_id=1
[65/190] Scraping: https://www.naiin.com/category?category_1_code=19&categoryLv2Code=30&product_type_id=1
[66/190] Scraping: https://www.naiin.com/category?category_1_code=19&categoryLv2Code=31&product_type_id=1
[67/190] Scraping: https://www.naiin.com/category?category_1_code=20&categoryLv2Code=66&product_type_id=1
[68/190] Scraping: https://www.naiin.com/category?category_1_code=27&categoryLv2Code=78&product_type_id=1
  [!] Status 404 for https://www.naiin.com/category?category_1_code=27&categoryLv2Code=78&product_type_id=1
[69/190] Scraping: https://www.naiin.com/category?category_1_code=28&categoryLv2Code=4&product_type_id=1
[70/190] Scraping: https://www.naiin.com/category?category_1_code=28&categoryLv2Code=87&product_type_id=1
[71/190] Scraping: https://www.naiin.com/category?category_1_code=28&categoryLv2Code=161&product_type_id=1
[72/190] Scraping: https://www.naiin.com/category?category_1_code=33&categoryLv2Code=1&product_type_id=1
[73/190] Scraping: https://www.naiin.com/category?category_1_code=33&categoryLv2Code=9&product_type_id=1
[74/190] Scraping: https://www.naiin.com/category?category_1_code=33&categoryLv2Code=55&product_type_id=1
[75/190] Scraping: https://www.naiin.com/category?category_1_code=33&categoryLv2Code=65&product_type_id=1
[76/190] Scraping: https://www.naiin.com/category?category_1_code=33&categoryLv2Code=159&product_type_id=1
  [!] Status 404 for https://www.naiin.com/category?category_1_code=33&categoryLv2Code=159&product_type_id=1
[77/190] Scraping: https://www.naiin.com/category?category_1_code=34&categoryLv2Code=18&product_type_id=1
[78/190] Scraping: https://www.naiin.com/category?category_1_code=34&categoryLv2Code=158&product_type_id=1
[79/190] Scraping: https://www.naiin.com/category?category_1_code=35&categoryLv2Code=131&product_type_id=1
[80/190] Scraping: https://www.naiin.com/category?category_1_code=36&categoryLv2Code=162&product_type_id=1
  [!] Status 404 for https://www.naiin.com/category?category_1_code=36&categoryLv2Code=162&product_type_id=1
[81/190] Scraping: https://www.naiin.com/category?category_1_code=35&categoryLv2Code=131&product_type_id=2
  [!] Status 404 for https://www.naiin.com/category?category_1_code=35&categoryLv2Code=131&product_type_id=2
[82/190] Scraping: https://www.naiin.com/category?category_1_code=36&categoryLv2Code=162&product_type_id=2
[83/190] Scraping: https://www.naiin.com/category?category_1_code=1&categoryLv2Code=54&product_type_id=3
[84/190] Scraping: https://www.naiin.com/category?category_1_code=1&categoryLv2Code=135&product_type_id=3
[85/190] Scraping: https://www.naiin.com/category?category_1_code=2&categoryLv2Code=6&product_type_id=3
[86/190] Scraping: https://www.naiin.com/category?category_1_code=2&categoryLv2Code=7&product_type_id=3
[87/190] Scraping: https://www.naiin.com/category?category_1_code=2&categoryLv2Code=8&product_type_id=3
[88/190] Scraping: https://www.naiin.com/category?category_1_code=2&categoryLv2Code=86&product_type_id=3
[89/190] Scraping: https://www.naiin.com/category?category_1_code=2&categoryLv2Code=134&product_type_id=3
[90/190] Scraping: https://www.naiin.com/category?category_1_code=3&categoryLv2Code=95&product_type_id=3
[91/190] Scraping: https://www.naiin.com/category?category_1_code=3&categoryLv2Code=140&product_type_id=3
[92/190] Scraping: https://www.naiin.com/category?category_1_code=4&categoryLv2Code=51&product_type_id=3
[93/190] Scraping: https://www.naiin.com/category?category_1_code=4&categoryLv2Code=52&product_type_id=3
[94/190] Scraping: https://www.naiin.com/category?category_1_code=4&categoryLv2Code=53&product_type_id=3
[95/190] Scraping: https://www.naiin.com/category?category_1_code=5&categoryLv2Code=56&product_type_id=3
[96/190] Scraping: https://www.naiin.com/category?category_1_code=8&categoryLv2Code=22&product_type_id=3
[97/190] Scraping: https://www.naiin.com/category?category_1_code=8&categoryLv2Code=57&product_type_id=3
[98/190] Scraping: https://www.naiin.com/category?category_1_code=8&categoryLv2Code=58&product_type_id=3
[99/190] Scraping: https://www.naiin.com/category?category_1_code=8&categoryLv2Code=59&product_type_id=3
[100/190] Scraping: https://www.naiin.com/category?category_1_code=9&categoryLv2Code=60&product_type_id=3
[101/190] Scraping: https://www.naiin.com/category?category_1_code=10&categoryLv2Code=61&product_type_id=3
[102/190] Scraping: https://www.naiin.com/category?category_1_code=11&categoryLv2Code=43&product_type_id=3
[103/190] Scraping: https://www.naiin.com/category?category_1_code=12&categoryLv2Code=62&product_type_id=3
[104/190] Scraping: https://www.naiin.com/category?category_1_code=13&categoryLv2Code=63&product_type_id=3
[105/190] Scraping: https://www.naiin.com/category?category_1_code=13&categoryLv2Code=139&product_type_id=3
[106/190] Scraping: https://www.naiin.com/category?category_1_code=14&categoryLv2Code=32&product_type_id=3
[107/190] Scraping: https://www.naiin.com/category?category_1_code=14&categoryLv2Code=33&product_type_id=3
[108/190] Scraping: https://www.naiin.com/category?category_1_code=14&categoryLv2Code=34&product_type_id=3
[109/190] Scraping: https://www.naiin.com/category?category_1_code=14&categoryLv2Code=35&product_type_id=3
[110/190] Scraping: https://www.naiin.com/category?category_1_code=14&categoryLv2Code=37&product_type_id=3
[111/190] Scraping: https://www.naiin.com/category?category_1_code=14&categoryLv2Code=38&product_type_id=3
[112/190] Scraping: https://www.naiin.com/category?category_1_code=14&categoryLv2Code=40&product_type_id=3
[113/190] Scraping: https://www.naiin.com/category?category_1_code=15&categoryLv2Code=47&product_type_id=3
[114/190] Scraping: https://www.naiin.com/category?category_1_code=15&categoryLv2Code=48&product_type_id=3
[115/190] Scraping: https://www.naiin.com/category?category_1_code=15&categoryLv2Code=49&product_type_id=3
[116/190] Scraping: https://www.naiin.com/category?category_1_code=15&categoryLv2Code=138&product_type_id=3
[117/190] Scraping: https://www.naiin.com/category?category_1_code=16&categoryLv2Code=64&product_type_id=3
[118/190] Scraping: https://www.naiin.com/category?category_1_code=16&categoryLv2Code=136&product_type_id=3
[119/190] Scraping: https://www.naiin.com/category?category_1_code=16&categoryLv2Code=137&product_type_id=3
[120/190] Scraping: https://www.naiin.com/category?category_1_code=17&categoryLv2Code=11&product_type_id=3
[121/190] Scraping: https://www.naiin.com/category?category_1_code=17&categoryLv2Code=14&product_type_id=3
[122/190] Scraping: https://www.naiin.com/category?category_1_code=17&categoryLv2Code=15&product_type_id=3
[123/190] Scraping: https://www.naiin.com/category?category_1_code=17&categoryLv2Code=16&product_type_id=3
[124/190] Scraping: https://www.naiin.com/category?category_1_code=17&categoryLv2Code=19&product_type_id=3
[125/190] Scraping: https://www.naiin.com/category?category_1_code=17&categoryLv2Code=20&product_type_id=3
[126/190] Scraping: https://www.naiin.com/category?category_1_code=17&categoryLv2Code=21&product_type_id=3
[127/190] Scraping: https://www.naiin.com/category?category_1_code=17&categoryLv2Code=23&product_type_id=3
[128/190] Scraping: https://www.naiin.com/category?category_1_code=17&categoryLv2Code=141&product_type_id=3
[129/190] Scraping: https://www.naiin.com/category?category_1_code=17&categoryLv2Code=142&product_type_id=3
[130/190] Scraping: https://www.naiin.com/category?category_1_code=17&categoryLv2Code=143&product_type_id=3
[131/190] Scraping: https://www.naiin.com/category?category_1_code=17&categoryLv2Code=144&product_type_id=3
[132/190] Scraping: https://www.naiin.com/category?category_1_code=17&categoryLv2Code=145&product_type_id=3
[133/190] Scraping: https://www.naiin.com/category?category_1_code=17&categoryLv2Code=146&product_type_id=3
[134/190] Scraping: https://www.naiin.com/category?category_1_code=17&categoryLv2Code=147&product_type_id=3
[135/190] Scraping: https://www.naiin.com/category?category_1_code=17&categoryLv2Code=148&product_type_id=3
[136/190] Scraping: https://www.naiin.com/category?category_1_code=17&categoryLv2Code=149&product_type_id=3
[137/190] Scraping: https://www.naiin.com/category?category_1_code=17&categoryLv2Code=150&product_type_id=3
[138/190] Scraping: https://www.naiin.com/category?category_1_code=17&categoryLv2Code=151&product_type_id=3
[139/190] Scraping: https://www.naiin.com/category?category_1_code=17&categoryLv2Code=152&product_type_id=3
[140/190] Scraping: https://www.naiin.com/category?category_1_code=17&categoryLv2Code=153&product_type_id=3
[141/190] Scraping: https://www.naiin.com/category?category_1_code=17&categoryLv2Code=154&product_type_id=3
[142/190] Scraping: https://www.naiin.com/category?category_1_code=17&categoryLv2Code=155&product_type_id=3
[143/190] Scraping: https://www.naiin.com/category?category_1_code=17&categoryLv2Code=156&product_type_id=3
[144/190] Scraping: https://www.naiin.com/category?category_1_code=17&categoryLv2Code=157&product_type_id=3
[145/190] Scraping: https://www.naiin.com/category?category_1_code=19&categoryLv2Code=24&product_type_id=3
[146/190] Scraping: https://www.naiin.com/category?category_1_code=19&categoryLv2Code=26&product_type_id=3
[147/190] Scraping: https://www.naiin.com/category?category_1_code=19&categoryLv2Code=30&product_type_id=3
[148/190] Scraping: https://www.naiin.com/category?category_1_code=19&categoryLv2Code=31&product_type_id=3
[149/190] Scraping: https://www.naiin.com/category?category_1_code=20&categoryLv2Code=66&product_type_id=3
[150/190] Scraping: https://www.naiin.com/category?category_1_code=28&categoryLv2Code=4&product_type_id=3
[151/190] Scraping: https://www.naiin.com/category?category_1_code=28&categoryLv2Code=87&product_type_id=3
[152/190] Scraping: https://www.naiin.com/category?category_1_code=28&categoryLv2Code=161&product_type_id=3
[153/190] Scraping: https://www.naiin.com/category?category_1_code=33&categoryLv2Code=1&product_type_id=3
[154/190] Scraping: https://www.naiin.com/category?category_1_code=33&categoryLv2Code=9&product_type_id=3
[155/190] Scraping: https://www.naiin.com/category?category_1_code=33&categoryLv2Code=55&product_type_id=3
[156/190] Scraping: https://www.naiin.com/category?category_1_code=33&categoryLv2Code=65&product_type_id=3
[157/190] Scraping: https://www.naiin.com/category?category_1_code=33&categoryLv2Code=159&product_type_id=3
[158/190] Scraping: https://www.naiin.com/category?category_1_code=34&categoryLv2Code=18&product_type_id=3
[159/190] Scraping: https://www.naiin.com/category?category_1_code=34&categoryLv2Code=158&product_type_id=3
[160/190] Scraping: https://www.naiin.com/category?category_1_code=17&categoryLv2Code=11&product_type_id=4
[161/190] Scraping: https://www.naiin.com/category?category_1_code=27&categoryLv2Code=78&product_type_id=4
[162/190] Scraping: https://www.naiin.com/category?category_1_code=35&categoryLv2Code=131&product_type_id=4
[163/190] Scraping: https://www.naiin.com/category?category_1_code=36&categoryLv2Code=162&product_type_id=4
[164/190] Scraping: https://www.naiin.com/category?category_1_code=27&categoryLv2Code=78&product_type_id=7
  [!] Status 404 for https://www.naiin.com/category?category_1_code=27&categoryLv2Code=78&product_type_id=7
[165/190] Scraping: https://www.naiin.com/category?category_1_code=35&categoryLv2Code=131&product_type_id=7
  [!] Status 404 for https://www.naiin.com/category?category_1_code=35&categoryLv2Code=131&product_type_id=7
[166/190] Scraping: https://www.naiin.com/category?category_1_code=36&categoryLv2Code=162&product_type_id=7
  [!] Status 404 for https://www.naiin.com/category?category_1_code=36&categoryLv2Code=162&product_type_id=7
[167/190] Scraping: https://www.naiin.com/category?category_1_code=21&categoryLv2Code=68&product_type_id=8
  [!] Status 404 for https://www.naiin.com/category?category_1_code=21&categoryLv2Code=68&product_type_id=8
[168/190] Scraping: https://www.naiin.com/category?category_1_code=21&categoryLv2Code=69&product_type_id=8
[169/190] Scraping: https://www.naiin.com/category?category_1_code=21&categoryLv2Code=71&product_type_id=8
[170/190] Scraping: https://www.naiin.com/category?category_1_code=21&categoryLv2Code=73&product_type_id=8
  [!] Status 404 for https://www.naiin.com/category?category_1_code=21&categoryLv2Code=73&product_type_id=8
[171/190] Scraping: https://www.naiin.com/category?category_1_code=21&categoryLv2Code=74&product_type_id=8
[172/190] Scraping: https://www.naiin.com/category?category_1_code=21&categoryLv2Code=133&product_type_id=8
  [!] Status 404 for https://www.naiin.com/category?category_1_code=21&categoryLv2Code=133&product_type_id=8

In [8]:
import os
import pandas as pd

# 1. get the current directory
current_directory = os.getcwd()

# 2. ระบุปลายทางไปที่โฟลเดอร์ /data
output_path = os.path.join(current_directory , "..", "data", "prod_cat_lv2.csv")

# 3. บันทึกไฟล์ด้วย Path ที่สร้างขึ้น
os.makedirs(os.path.dirname(output_path), exist_ok=True)
cat_lv2_df.to_csv(output_path, index=False, encoding='utf-8-sig', mode = 'w')

print(f"✅ Saved product URLs to: {output_path}")

✅ Saved product URLs to: d:\Project\book-scrap\ingestion\..\data\prod_cat_lv2.csv

# Create product type id

In [2]:
import pandas as pd
import os

In [3]:
# manual check for product type_id
product_type_id_kv = {
    "product_type_id": [1, 2, 3, 4, 8],
    "product_type_description": ["หนังสือ", "นิตยสาร", "อีบุ๊ก", "อีแม็กกาซีน", "ไลฟ์สไตล์แอนด์กิ๊ฟ"]
}

In [4]:
product_type_df = pd.DataFrame(product_type_id_kv)
product_type_df

   product_type_id product_type_description
0                1                  หนังสือ
1                2                  นิตยสาร
2                3                   อีบุ๊ก
3                4              อีแม็กกาซีน
4                8       ไลฟ์สไตล์แอนด์กิ๊ฟ

In [7]:
# 1. get the current directory
current_directory = os.getcwd()

# 2. ระบุปลายทางไปที่โฟลเดอร์ /data
output_path = os.path.join(current_directory , "..", "data", "product_type.csv")

# 3. บันทึกไฟล์ด้วย Path ที่สร้างขึ้น
os.makedirs(os.path.dirname(output_path), exist_ok=True)
product_type_df.to_csv(output_path, index=False, encoding='utf-8-sig')

# Get product details url for scraping

In [3]:
import requests
from bs4 import BeautifulSoup
import time
import pandas as pd
import datetime

In [4]:
SITEMAP_INDEX_URLS = [
    f"https://storage.naiin.com/system/application/bookstore/resource/sitemap/sitemap_ProductDetail-{i}.xml"
    for i in range(1, 6)
]

In [5]:
HEADERS = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8',
    'Accept-Language': 'th-TH,th;q=0.9,en-US;q=0.8,en;q=0.7',
    'Referer': 'https://www.naiin.com/',
}

In [6]:
def get_book_urls(url):
    print(f"Opening sub-sitemap: {url}")
    try:
        # ใช้ lxml-xml เพื่อความเร็วในการ parse XML ขนาดใหญ่
        response = requests.get(url, headers=HEADERS, timeout=30)
        soup = BeautifulSoup(response.content, 'lxml-xml')

        all_book_urls = [loc.text for loc in soup.find_all("loc")]
        print(f"Found {len(all_book_urls)} total books.")
        return all_book_urls
    except Exception as e:
        print(f"Error accessing sitemap {url}: {e}")
        return []

In [7]:
def get_all_book_url(SITEMAP_INDEX_URLS):
    all_results = []
    for sitemap_url in SITEMAP_INDEX_URLS:
        urls = get_book_urls(sitemap_url)
        
        for u in urls:
            # 1. ตัด / ที่ปิดท้ายออกก่อน แล้วค่อย split
            # ตัวอย่าง: ".../detail/123/" -> ".../detail/123" -> "123"
            p_id = u.strip('/').split('/')[-1]
            
            # 2. ป้องกันกรณีที่ url อาจจะสั้นเกินไปจนไม่ใช่ id
            if p_id:
                all_results.append({
                    'product_id': p_id,
                    'url': u,
                    'status': 'pending',
                    'discovered_at': datetime.datetime.now()
                })

    df = pd.DataFrame(all_results)
    
    # ตรวจสอบเบื้องต้น: ถ้ายังมี null ให้ drop ทิ้งไปเลย
    df = df.dropna(subset=['product_id'])
    
    return df

In [8]:
products_url = get_all_book_url(SITEMAP_INDEX_URLS)

Opening sub-sitemap: https://storage.naiin.com/system/application/bookstore/resource/sitemap/sitemap_ProductDetail-1.xml
Found 40000 total books.
Opening sub-sitemap: https://storage.naiin.com/system/application/bookstore/resource/sitemap/sitemap_ProductDetail-2.xml
Found 40000 total books.
Opening sub-sitemap: https://storage.naiin.com/system/application/bookstore/resource/sitemap/sitemap_ProductDetail-3.xml
Found 40000 total books.
Opening sub-sitemap: https://storage.naiin.com/system/application/bookstore/resource/sitemap/sitemap_ProductDetail-4.xml
Found 40000 total books.
Opening sub-sitemap: https://storage.naiin.com/system/application/bookstore/resource/sitemap/sitemap_ProductDetail-5.xml
Found 26966 total books.

In [9]:
products_url.count()

product_id       186966
url              186966
status           186966
discovered_at    186966
dtype: int64

In [ ]:
import os
import pandas as pd

# 1. กำหนดฐานของโปรเจกต์ (ถอยกลับไป 1 step จาก /ingestion)
base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# 2. ระบุปลายทางไปที่โฟลเดอร์ /data
output_path = os.path.join(base_dir, "data", "prod_urls.csv")

# 3. บันทึกไฟล์ด้วย Path ที่สร้างขึ้น
os.makedirs(os.path.dirname(output_path), exist_ok=True)
products_url.to_csv(output_path, index=False)

print(f"✅ Saved product URLs to: {output_path}")